version: "3.8"

services:

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "7025:8025"
    restart: unless-stopped

  db:
    image: postgres:14.1-alpine
    env_file:
      - ./confs/enabled/db.env
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
    restart: unless-stopped

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - ./volumes/redis-data:/data
    restart: unless-stopped

  moodle:
    image: "ctezlifrn/install_ifrn:3.11.4.001"
    # image: ctezlifrn/moodle:3.11.4
    volumes:
      - "./volumes/moodledata:/var/moodledata"
      - "./volumes/moodledata/antivirus_quarantine:/var/moodledata/antivirus_quarantine"
      - "./volumes/moodledata/cache:/var/moodledata/cache"
      - "./volumes/moodledata/filedir:/var/moodledata/filedir"
      - "./volumes/moodledata/lang:/var/moodledata/lang"
      - "./volumes/moodledata/localcache:/var/moodledata/localcache"
      - "./volumes/moodledata/lock:/var/moodledata/lock"
      - "./volumes/moodledata/muc:/var/moodledata/muc"
      - "./volumes/moodledata/sessions:/var/moodledata/sessions"
      - "./volumes/moodledata/temp:/var/moodledata/temp"
      - "./volumes/moodledata/trashdir:/var/moodledata/trashdir"
      - "./volumes/custom_logs:/var/custom_logs/"
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/moodle.env
    ports:
      - "${MOODLE_DOCKER_APACHE_PORT}:80"
    restart: unless-stopped
